[package]
name = "serde_codegen"
version = "0.6.14"
authors = ["Erick Tryzelaar <erick.tryzelaar@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Macros to auto-generate implementations for the serde framework"
repository = "https://github.com/serde-rs/serde"
documentation = "https://serde-rs.github.io/serde/serde_codegen/serde_codegen/index.html"
build = "build.rs"
keywords = ["serde", "serialization"]

[features]
default = ["with-syntex"]
nightly = ["quasi_macros"]
nightly-testing = ["clippy"]
with-syntex = ["quasi/with-syntex", "quasi_codegen", "quasi_codegen/with-syntex", "syntex", "syntex_syntax"]

[build-dependencies]
quasi_codegen = { version = "^0.7.0", optional = true }
syntex = { version = "^0.29.0", optional = true }

[dependencies]
aster = { version = "^0.13.1", default-features = false }
clippy = { version = "^0.*", optional = true }
quasi = { version = "^0.7.0", default-features = false }
quasi_macros = { version = "^0.7.0", optional = true }
syntex = { version = "^0.29.0", optional = true }
syntex_syntax = { version = "^0.29.0", optional = true }
