[package]
name = "serde_codegen"
version = "0.7.10"
authors = ["Erick Tryzelaar <erick.tryzelaar@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Macros to auto-generate implementations for the serde framework"
repository = "https://github.com/serde-rs/serde"
documentation = "https://github.com/serde-rs/serde"
keywords = ["serde", "serialization"]
build = "build.rs"
include = ["Cargo.toml", "build.rs", "src/**/*.rs", "src/lib.rs.in"]

[features]
default = ["with-syntex"]
nightly = ["quasi_macros"]
nightly-testing = ["clippy"]
with-syntex = ["quasi/with-syntex", "quasi_codegen", "quasi_codegen/with-syntex", "syntex", "syntex_syntax"]

[build-dependencies]
quasi_codegen = { version = "^0.12.0", optional = true }
syntex = { version = "^0.33.0", optional = true }

[dependencies]
aster = { version = "^0.18.0", default-features = false }
clippy = { version = "^0.*", optional = true }
quasi = { version = "^0.12.0", default-features = false }
quasi_macros = { version = "^0.12.0", optional = true }
syntex = { version = "^0.35.0", optional = true }
syntex_syntax = { version = "^0.35.0", optional = true }
