[package]
name = "serde_codegen"
version = "0.8.1"
authors = ["Erick Tryzelaar <erick.tryzelaar@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Macros to auto-generate implementations for the serde framework"
repository = "https://github.com/serde-rs/serde"
documentation = "https://github.com/serde-rs/serde"
keywords = ["serde", "serialization"]
build = "build.rs"
include = ["Cargo.toml", "build.rs", "src/**/*.rs", "src/lib.rs.in"]

[features]
default = ["with-syntex"]
unstable = ["quasi_macros"]
unstable-testing = ["clippy"]
with-syntex = [
    "quasi/with-syntex",
    "quasi_codegen",
    "quasi_codegen/with-syntex",
    "serde_codegen_internals/with-syntex",
    "syntex",
    "syntex_syntax",
]

[build-dependencies]
quasi_codegen = { version = "^0.16.0", optional = true }
syntex = { version = "^0.39.0", optional = true }

[dependencies]
aster = { version = "^0.22.0", default-features = false }
clippy = { version = "^0.*", optional = true }
quasi = { version = "^0.16.0", default-features = false }
quasi_macros = { version = "^0.16.0", optional = true }
serde_codegen_internals = { version = "=0.5.0", default-features = false }
syntex = { version = "^0.39.0", optional = true }
syntex_syntax = { version = "^0.39.0", optional = true }
