sudo: false
language: rust
rust:
- 1.13.0
- stable
- beta
- nightly
before_script:
- pip install 'travis-cargo<0.2' --user
- export PATH=$HOME/.local/bin:$PATH
script:
- (cd serde && travis-cargo build)
- (cd serde && travis-cargo --only beta test)
- (cd serde && travis-cargo --only nightly test -- --features unstable-testing)
- (cd serde && travis-cargo build -- --no-default-features)
- (cd serde && travis-cargo --only nightly build -- --no-default-features --features alloc)
- (cd serde && travis-cargo --only nightly build -- --no-default-features --features collections)
- (cd test_suite && travis-cargo --only beta test)
- (cd test_suite && travis-cargo --only nightly test -- --features unstable-testing)
- (cd test_suite/no_std && travis-cargo --only nightly build)
- (cd serde && travis-cargo --only stable doc)
env:
  global:
  - TRAVIS_CARGO_NIGHTLY_FEATURE=""
