[package]
name = "serde_test_suite_deps"
version = "0.0.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
publish = false

[workspace]

[dependencies]
serde = { path = "../../serde" }
serde_derive = "1.0"
serde_derive_seed = { path = "../../serde_derive" }
