[package]
name = "serde_macros"
version = "0.6.12"
authors = ["Erick Tryzelaar <erick.tryzelaar@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Macros to auto-generate implementations for the serde framework"
repository = "https://github.com/serde-rs/serde"
documentation = "https://github.com/serde-rs/serde"
keywords = ["serde", "serialization"]

[lib]
name = "serde_macros"
plugin = true

[features]
nightly-testing = ["clippy", "serde/nightly-testing", "serde_codegen/nightly-testing"]

[dependencies]
clippy = { version = "^0.0.39", optional = true }
serde_codegen = { version = "^0.6.12", path = "../serde_codegen", default-features = false, features = ["nightly"] }

[dev-dependencies]
compiletest_rs = "^0.0.11"
num = "^0.1.27"
rustc-serialize = "^0.3.16"
serde = { version = "^0.6.12", path = "../serde", features = ["num-impls"] }

[[test]]
name = "test"
path = "tests/test.rs"

[[bench]]
name = "bench"
path = "benches/bench.rs"
