[package]
name = "serde_macros"
version = "0.4.0"
authors = ["Erick Tryzelaar <erick.tryzelaar@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Macros to auto-generate implementations for the serde framework"
repository = "https://github.com/erickt/rust-serde"

[lib]
name = "serde_macros"
plugin = true

[dependencies]
aster = "*"
quasi = "*"
quasi_macros = "*"
