[package]
name = "serde_derive_tests_no_std"
version = "0.0.0"
publish = false

[dependencies]
libc = { version = "0.2", default-features = false }
serde = { path = "../../serde", default-features = false }
serde_derive = "1.0"
serde_derive_seed = { path = "../../serde_derive" }
