[package]
name = "serde_derive_tests_no_std"
version = "0.0.0"
publish = false

[dependencies]
libc = { version = "0.2", default-features = false }
serde = { path = "../../serde", default-features = false }
serde_derive = { path = "../../serde_derive" }

[workspace]

[patch.crates-io]
failure = { git = "https://github.com/withoutboats/failure" }
